// import { AuctionWithBids } from "../types/auction";

// export const mockAuctions: AuctionWithBids[] = [
//   {
//     id: 1,
//     title: "Auction 1",
//     description: "Description 1",
//     photo: "https://picsum.photos/200/200",
//     numOfWinners: 1,
//     is_paid: false,
//     is_collected: false,
//     min_bid_value: 100,
//     auction_end_data: new Date(),
//     deadline: new Date(),
//     bids: [
//       {
//         id: 1,
//         auctionId: 1,
//         userId: 1,
//         price: 100,
//         date: new Date(),
//       },
//       {
//         id: 2,
//         auctionId: 1,
//         userId: 2,
//         price: 200,
//         date: new Date(),
//       },
//       {
//         id: 3,
//         auctionId: 1,
//         userId: 3,
//         price: 300,
//         date: new Date(),
//       },
//     ],
//   },
//   {
//     id: 2,
//     title: "Auction 2",
//     description: "Description 2",
//     photo: "https://picsum.photos/200/200",
//     numOfWinners: 1,
//     isPaid: false,
//     is_collected: false,
//     min_bid_value: 100,
//     auction_end_data: new Date(),
//     deadline: new Date(),
//     bids: [
//       {
//         id: 4,
//         auctionId: 2,
//         userId: 1,
//         price: 100,
//         date: new Date(),
//       },
//       {
//         id: 5,
//         auctionId: 2,
//         userId: 2,
//         price: 200,
//         date: new Date(),
//       },
//       {
//         id: 6,
//         auctionId: 2,
//         userId: 3,
//         price: 300,
//         date: new Date(),
//       },
//     ],
//   },
//   {
//     id: 3,
//     title: "Auction 3",
//     description: "Description 3",
//     photo: "https://picsum.photos/200/200",
//     numOfWinners: 1,
//     isPaid: false,
//     is_collected: false,
//     min_bid_value: 100,
//     auction_end_data: new Date(),
//     deadline: new Date(),
//     bids: [
//       {
//         id: 7,
//         auctionId: 3,
//         userId: 1,
//         price: 100,
//         date: new Date(),
//       },
//       {
//         id: 8,
//         auctionId: 3,
//         userId: 2,
//         price: 200,
//         date: new Date(),
//       },
//       {
//         id: 9,
//         auctionId: 3,
//         userId: 3,
//         price: 300,
//         date: new Date(),
//       },
//     ],
//   },
//   {
//     id: 4,
//     title: "Auction 4",
//     description: "Description 4",
//     photo: "https://picsum.photos/200/200",
//     numOfWinners: 1,
//     isPaid: false,
//     is_collected: false,
//     min_bid_value: 100,
//     auction_end_data: new Date(),
//     deadline: new Date(),
//     bids: [],
//   },
//   {
//     id: 5,
//     title: "Auction 5",
//     description: "Description 5",
//     photo: "https://picsum.photos/200/200",
//     numOfWinners: 1,
//     isPaid: false,
//     is_collected: false,
//     min_bid_value: 100,
//     auction_end_data: new Date(),
//     deadline: new Date(),
//     bids: [],
//   },
//   {
//     id: 6,
//     title: "Auction 6",
//     description: "Description 6",
//     photo: "https://picsum.photos/200/200",
//     numOfWinners: 1,
//     isPaid: false,
//     is_collected: false,
//     min_bid_value: 100,
//     auction_end_data: new Date(),
//     deadline: new Date(),
//     bids: [
//       {
//         id: 10,
//         auctionId: 6,
//         userId: 1,
//         price: 100,
//         date: new Date(),
//       },
//       {
//         id: 11,
//         auctionId: 6,
//         userId: 2,
//         price: 200,
//         date: new Date(),
//       },
//       {
//         id: 12,
//         auctionId: 6,
//         userId: 3,
//         price: 300,
//         date: new Date(),
//       },
//     ],
//   },
//   {
//     id: 7,
//     title: "Auction 7",
//     description: "Description 7",
//     photo: "https://picsum.photos/200/200",
//     numOfWinners: 1,
//     isPaid: false,
//     is_collected: false,
//     min_bid_value: 100,
//     auction_end_data: new Date(),
//     deadline: new Date(),
//     bids: [],
//   },
//   {
//     id: 8,
//     title: "Auction 8",
//     description: "Description 8",
//     photo: "https://picsum.photos/200/200",
//     numOfWinners: 1,
//     isPaid: false,
//     is_collected: false,
//     min_bid_value: 100,
//     auction_end_data: new Date(),
//     deadline: new Date(),
//     bids: [],
//   },
//   {
//     id: 9,
//     title: "Auction 9",
//     description: "Description 9",
//     photo: "https://picsum.photos/200/200",
//     numOfWinners: 1,
//     isPaid: false,
//     is_collected: false,
//     min_bid_value: 100,
//     auction_end_data: new Date(),
//     deadline: new Date(),
//     bids: [],
//   },
//   {
//     id: 10,
//     title: "Auction 10",
//     description: "Description 10",
//     photo: "https://picsum.photos/200/200",
//     numOfWinners: 1,
//     isPaid: false,
//     is_collected: false,
//     min_bid_value: 100,
//     auction_end_data: new Date(),
//     deadline: new Date(),
//     bids: [],
//   },
// ];
