# Generated by Django 4.2.6 on 2023-12-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='photo',
        ),
        migrations.AddField(
            model_name='auction',
            name='photo_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
